### ISSUE TITLE
Using Retain for multiclass problem

### ISSUE THREAD

**Issue by priyakumari85** [mp2893/retain#5]
Hi Edward,

This is more of a question on Retain paper and not on the actual code.
I have a usecase where RETAIN can be a good possible solution however, the problem is multi-class(5 classes) in nature.
I am interested to hear your initial thoughts on my approach -  
  if I implement attention mechanism in the same way explained in RETAIN paper but the model architecture is enhanced to predict multi-class as output (i.e. I will have one set of alpha, beta and context however,  5 nodes in output layer). 

Do you expect attention mechanism and interpretation to still hold good with my above approach? Does having just one context vector for five classes make sense?

Thanks in advance!
-Priya

**Comment by mp2893** [comment]
Hi Priya,

Actually, in the RETAIN paper, the equation for calculating the contribution of the codes is formulated under the assumption of a multi-class classification problem.
You can check that in Eq.2, y is boldface. 
So yes, RETAIN will work just fine for 5-class classification as well.

Best,
Ed

**Comment by priyakumari85** [comment]
Thanks for quick response! This is great work.
