### ISSUE TITLE
Feeding sequence in inverse order

### ISSUE THREAD

**Issue by Usama1002** [mp2893/retain#6]
Hi,

My query is more like a question than an issue. I am a bit confused about the following foot note in your paper (image attached).

![Screenshot from 2020-05-06 21-27-11](https://user-images.githubusercontent.com/34058701/81176696-78c76080-8fe0-11ea-952b-931569ea9ce4.png)

My query is that why feeding the sequence in forward order will generate the same e_1 and beta_1 as they depend on learnable parameters also ?

Regards,

Usama.

**Comment by mp2893** [comment]
Hi Usama,

Thanks for taking interest in RETAIN.
What we meant by "feeding the sequence in forward order will generate the same e_1 and beta_1" is: 
If you feed visit_1, visit_2 and visit_3 in order, then e_1 will be generated before e_2, and e_2 will be generated by e_3, obviously. This means that feeding n-th visit to the RNN_alpha won't change the value of e_1, ..., e_{n-1}. Of course the values of e_1, ..., e_n will change after each parameter update. Hope this clear things up.

Best,
Ed
